language: java

jdk:
  - oraclejdk8
    
install: true
script:
- mvn -U clean package com.blackducksoftware.integration:hub-maven-plugin:1.4.0:createHubOutput
  
after_success:
- mvn jacoco:report coveralls:report 
- bash <(curl -s https://test.duckbuild.io/bash/travis) ./target/blackduck/hub-common_bdio.jsonld 
