language: java
notifications:
  email:
    recipients:
      - akamen@blackducksoftware.com
      - jrichard@blackducksoftware.com
      - psantos@blackducksoftware.com
      - ekerwin@blackducksoftware.com

install: true
# Run maven, but skip tests for now as they require Hub instance.
script:
  - mvn package -DskipTests=true
after_success:
#  - mvn test jacoco:report coveralls:report
