language: java

jdk:
  - oraclejdk8
    
install: true
script:
- mvn -U clean package 
  
after_success:
- mvn jacoco:report coveralls:report 
- mvn com.blackducksoftware.integration:hub-maven-plugin:1.4.0:createHubOutput -Dhub.output.directory=.
- bash <(curl -s https://test.duckbuild.io/bash/travis) ./*bdio.jsonld 
